### ISSUE TITLE
[Some complain]: Roslyn Source generator support badly for net8.0

### ISSUE THREAD

**Issue by Sieluna** [sicusa/Sia.NET#5]
### Description

I think it is good to remove the net8.0 from compile target. Here I will provide some comparisons:

1. The nuget will load netstandard 2.0 target only (didn't upload the net8.0).
![image](https://github.com/sicusa/Sia.NET/assets/88884784/4e4183e2-5a21-42e5-992c-e2028216fb09)

2. The net8.0 build will use locally only. This will cause a analyse fault for Roslyn analyser. (You can reproduce the effect by reclone the project from git)
![image](https://github.com/sicusa/Sia.NET/assets/88884784/1876f4cb-317c-4e62-9982-c97bcadaeb4e)
![image](https://github.com/sicusa/Sia.NET/assets/88884784/21c785e5-4448-4d4c-a9ae-dc99cf7b14d2)

3. Let's remove the net8.0 at
https://github.com/sicusa/Sia.NET/blob/c71a9bceb87054facb5f28765dbafd5323460aca/Sia.CodeGenerators/Sia.CodeGenerators.csproj#L4
```diff
+   <TargetFramework>netstandard2.0</TargetFramework>
-    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
```
1. No any error message from Roslyn analyser.
2. IDE can recognize the generated source successfully.
![image](https://github.com/sicusa/Sia.NET/assets/88884784/ef353662-2d8f-4357-8f74-ae02b7a797a3)
![image](https://github.com/sicusa/Sia.NET/assets/88884784/18734d84-7ccf-48fe-a1fe-ad02ef341782)

**Comment by sicusa** [comment]
Thanks~
